steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--no-optional']
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build' ]
- name: 'gcr.io/${PROJECT_ID}/firebase'
  args: [ 'deploy', '--project', '${PROJECT_ID}', '--token', '"$$FIREBASE_TOKEN"', '--only', 'hosting']
  secretEnv: ['FIREBASE_TOKEN']


secrets:
- kmsKeyName: 'projects/x-dev-ew3/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
  secretEnv:
    FIREBASE_TOKEN: 'CiQA8wnE9EvkcUw6pNSSxSk4UejggM70p1qM7N5IRjPZO1U7RoISbQBYl1a7rq7hJFce/UC+bkvtqMAHIhIIB6MltO7PO2jph34oC3FF3K0gzQDHjVGim1y7llDgbQGn0CL4eOm3XZlNOj2uLnzVYxNkyf6LTAAcVYb8DVI1bqKo/xa2pdrgHrxU+trkECXr6M0AXiQ='
