steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--no-optional']
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build' ]
- name: 'gcr.io/${PROJECT_ID}/firebase'
  args: [ 'deploy', '--project', '${PROJECT_ID}', '--token', '"$$FIREBASE_TOKEN"', '--only', 'hosting']
  secretEnv: ['FIREBASE_TOKEN']


secrets:
- kmsKeyName: 'projects/x-dev-ew3/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-secret'
  secretEnv:
    FIREBASE_TOKEN: 'CiQAc4FKcTbzamIoUWmvWhJRQ6ls1icODwy4h5xmum5vgYvAnhwSawC3Upsdv9Yxwwg8prtuVieJZTx9UYkYVE/jpE70KhoYlteCSsHguxpPPxFwyhpiocBiLch+DeqMECshvlvORTYvy71IKQqJg9xab8HtPJcFPLNud964Whcx/bzzNiOk2diK6gV8EzmhNVtr'
